# Generated by Django 2.1.7 on 2019-05-11 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestTransData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(default='123 456 78 90', max_length=32)),
                ('email', models.CharField(default='kontakt@besttrans.com.pl', max_length=32)),
                ('phone_number', models.CharField(default='111222333', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapping', models.CharField(default='', max_length=256)),
                ('pallets_number', models.IntegerField()),
                ('remarks', models.TextField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('card_drive_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('remarks', models.TextField(default='', max_length=256)),
                ('palette_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='InquiriesOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InquiriesOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InquiriesResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text_or_remarks', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('email', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('readed', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallets_number', models.IntegerField()),
                ('remarks', models.TextField(default='', max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(blank=True, max_length=32, null=True)),
                ('destination', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_place_offer', to='api.ExtendAddress')),
                ('loading_place', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_place_offer', to='api.ExtendAddress')),
            ],
        ),
        migrations.CreateModel(
            name='OffersVehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('remarks', models.TextField(default='', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDestinationPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ExtendAddress')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDrivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Driver')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersLoadingPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ExtendAddress')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Offer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersVehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('tax_number', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsesProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseToCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('readed', models.BooleanField(default=False)),
                ('receiver', models.ManyToManyField(related_name='responses_profiles', through='api.ResponsesProfiles', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('post_code', models.CharField(max_length=128)),
                ('post_place', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('kind', models.CharField(blank=True, max_length=64, null=True)),
                ('registration_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='responsesprofiles',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ResponseToCustomer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SimpleAddress'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Company'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersvehicles',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Vehicle'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='destinations',
            field=models.ManyToManyField(related_name='order_destination_places', through='api.OrdersDestinationPlaces', to='api.ExtendAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='drivers',
            field=models.ManyToManyField(blank=True, through='api.OrdersDrivers', to='api.Driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='loading_places',
            field=models.ManyToManyField(related_name='order_loading_places', through='api.OrdersLoadingPlaces', to='api.ExtendAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='offers',
            field=models.ManyToManyField(blank=True, through='api.OrdersOffers', to='api.Offer'),
        ),
        migrations.AddField(
            model_name='order',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.BestTransData'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicles',
            field=models.ManyToManyField(blank=True, through='api.OrdersVehicles', to='api.Vehicle'),
        ),
        migrations.AddField(
            model_name='offersvehicles',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Vehicle'),
        ),
        migrations.AddField(
            model_name='offer',
            name='vehicles',
            field=models.ManyToManyField(through='api.OffersVehicles', to='api.Vehicle'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries_customer', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='inquiries_offers', through='api.InquiriesOffers', to='api.Offer'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='inquiries_orders', through='api.InquiriesOrders', to='api.Order'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='inquiries_responses', through='api.InquiriesResponses', to='api.ResponseToCustomer'),
        ),
        migrations.AddField(
            model_name='inquiriesresponses',
            name='inquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Inquiry'),
        ),
        migrations.AddField(
            model_name='inquiriesresponses',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ResponseToCustomer'),
        ),
        migrations.AddField(
            model_name='inquiriesorders',
            name='inquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Inquiry'),
        ),
        migrations.AddField(
            model_name='inquiriesorders',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Order'),
        ),
        migrations.AddField(
            model_name='inquiriesoffers',
            name='inquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Inquiry'),
        ),
        migrations.AddField(
            model_name='inquiriesoffers',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Offer'),
        ),
        migrations.AddField(
            model_name='extendaddress',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SimpleAddress'),
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SimpleAddress'),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SimpleAddress'),
        ),
        migrations.AddField(
            model_name='besttransdata',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.SimpleAddress'),
        ),
    ]
