# Generated by Django 2.1.7 on 2019-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendaddress',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='extendaddress',
            name='hour',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
