from api.others import *
from api.handling_pressing_item_of_dialogflow_list import *

intents = {
    "Default Welcome Intent": default_welcome_intent,
    "Others": others,
    "Contact": contact,
    "About us": about_us,
    "Address": address,
    "Car fleet": car_fleet,
    "Account": account,
    "Values of lists": values_of_lists,
    "Access Google account": access_google_account,
    "After sign in": after_sign_in,
    "Delete account": delete_account,
    "Delete account - yes": delete_account_yes,
    "Delete account - no": delete_account_no,
    "One user information": one_user_information,
    "Tell username": tell_username,
    "Tell name": tell_name,
    "Tell surname": tell_surname,
    "Tell email": tell_email,
    "Tell phone number": tell_phone_number,
    "Tell tax number": tell_tax_number,
    "Tell place name": tell_place_name,
    "Tell street": tell_street,
    "Tell post code": tell_post_code,
    "Tell post place": tell_post_place,
    "Tell country": tell_country,
    "Tell company tax number": tell_company_tax_number,
    "Tell company email": tell_company_email,
    "Tell company phone number": tell_company_phone_number,
    "Tell company name": tell_company_name,
    "Tell company street": tell_company_street,
    "Tell company post code": tell_company_post_code,
    "Tell company post place": tell_company_post_place,
    "Tell company country": tell_company_country,
    "Tell all account information": tell_all_account_information,
    "Ask change account settings": ask_change_account_settings,
    "Change personal data settings": change_personal_data_settings,
    "Change personal settings - yes": change_personal_settings_yes,
    "Change personal settings - no": change_personal_settings_no,
    "Change company data settings": change_company_data_settings,
    "Change company settings - yes": change_company_settings_yes,
    "Change company settings - no": change_company_settings_no,
    "Change one account information": change_one_account_information,
    "Change user name": change_user_name,
    "Change user name - custom": change_user_name_custom,
    "Change user surname": change_user_surname,
    "Change user surname - custom": change_user_surname_custom,
    "Change user username": change_user_username,
    "Change user username - custom": change_user_username_custom,
    "Change user password": "",
    "Change user password - custom": "",
    "Change user email": "",
    "Change user email - custom": "",
    "Offers": offers,
    "Inquiries": inquiries,
    "Browse offers": browse_offers,
    "Ask search offers": ask_search_offers,
    "Search offers": search_offers,
    "Ask search offer after id": ask_search_offer_id,
    "Search offer id": search_offer_id,
    "Ask until when offer valid": ask_until_when_offer_valid,
    "Check offer valid": check_offer_valid,
    "Check offer valid id": check_offer_valid_id,
    "Create a inquiry": create_inquiry,
    "Get inquiry title ask text": get_inquiry_title_ask_text,
    "Get inquiry text": get_inquiry_text,
    "Get email and phone number for inquiry": get_email_phone_for_inquiry,
    "Search inquiry or response": search_inquiry_response,
    "Ask search response": ask_search_response,
    "Ask search inquiry": ask_search_inquiry,
    "Search inquiry": search_inquiry,
    "Search response": search_response,
    "Ask creating inquiry for": ask_creating_inquiry_for,
    "Ask search offer for creating inquiry": ask_search_offer_for_creating_inquiry,
    "Ask search order for creating inquiry": ask_search_order_for_creating_inquiry,
    "Get offers for inquiry": get_offers_for_inquiry,
    "Are there unread responses": are_there_unread_responses,
    "Unread responses": unread_responses,
    "Ask responses for inquiry": ask_responses_for_inquiry,
    "Responses for inquiry": responses_for_inquiry,
    "Ask search response for": ask_search_response_for,
    "Ask search response for offer": ask_search_response_for_offer,
    "Search responses for offer": search_responses_for_offer,
    "Ask create response to admin": ask_create_response_to_admnin,
    "Create response to admin": create_response_to_admin,
    "Orders": orders,
    "Browse current orders": browse_current_orders,
    "The history of orders": orders_history,
    "Order number": order_number,
    "Ask search orders": ask_search_orders,
    "Search order": search_orders,
    "Ask order accepted for execution": ask_order_accepted,
    "Check order accepted for execution": check_order_accepted_for_execution,
    "Ask order realised": ask_order_realised,
    "Check order realised": check_order_realised,
    "Ask remove order": ask_remove_order,
    "Remove order": remove_order,
    "Remove order - no": remove_order_no,
    "Remove order - yes": remove_order_yes,
    "Ask create order": ask_create_order,
    "Create order loadings places dates": create_order_loadings_places_dates,
    "Create order loadings dates": create_order_loadings_dates,
    "Create order destinations places dates": create_order_destinations_places_dates,
    "Create order destinations dates": create_order_destinations_dates,
    "Create order destinations dates - yes": create_order_destinations_dates_yes,
    "Create order destinations dates - no": create_order_destinations_dates_no,
    "Create order additional notes": create_order_additional_notes,
    "Create order price": create_order_price,
    "Create order telephone email": create_order_email_phone_number,
    "Create order": create_order,
    "Create order - no": create_order_no,
    "Create order - yes": create_order_yes
}
